config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  authenticated :user, -> user { user.admin? }  do
    mount DelayedJobWeb, at: "/delayed_job"
  end

  match "/admin/import_specs/change_subcategories" => 'admin/import_specs#change_subcategories',  via: :post
  match "/admin/import_specs/change_specs"         => 'admin/import_specs#change_specs',          via: :post
  match "/admin/import_specs/change_origin_specs"  => 'admin/import_specs#change_origin_specs',   via: :post
  match "/admin/import_specs/change_spec_examples" => 'admin/import_specs#change_spec_examples',  via: :post

  match "/admin/import_specs/:id/change_subcategories" => 'admin/import_specs#change_subcategories',  via: :post
  match "/admin/import_specs/:id/change_specs"         => 'admin/import_specs#change_specs',          via: :post
  match "/admin/import_specs/:id/change_origin_specs"  => 'admin/import_specs#change_origin_specs',   via: :post
  match "/admin/import_specs/:id/change_spec_examples" => 'admin/import_specs#change_spec_examples',  via: :post

  match "/admin/page_departments/url_example" => 'admin/page_departments#url_example',  via: :post
  match "/admin/page_departments/:id/url_example" => 'admin/page_departments#url_example',  via: :post

  devise_for :users

  resources :public do
    get 'products', on: :collection
  end
  resources :price_categories
  resources :csv_errors
  resources :products
  resources :files do
    post :upload, on: :collection
    get :send_daily_reports, on: :collection
    get :send_top_seller_report, on: :collection
  end

  match "benchmark"          => "benchmark#index", via: [:get, :post]
  match "benchmark/products" => "benchmark#products", via: :get
  match "map"                => "minimum_advertised_price#index", via: :get
  match "price_evolution"    => "price_evolution#index", via: [:get, :post]

  match "product_evolution"     => "product_evolution#index", via: :get
  match "product_evolution/:id" => "product_evolution#show", via: [:get, :post], as: :show_product_evolution

  root to: 'public#index'
end

app/models/csv_error.rb
# == Schema Information
#
# Table name: csv_errors
#
#  id          :integer          not null, primary key
#  source_line :text
#  error       :string
#  mode        :string
#  parser      :string
#  category    :string
#  warn        :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  n           :integer
#  date        :date
#

class CsvError < ApplicationRecord

  scope :like_source_line,  -> (line)    { where('source_line LIKE ?', "%#{line}%") }
  scope :like_error,        -> (error)   { where('error LIKE ?', "%#{error}%") }
  scope :warn,              ->           { where('warn IS true' ) }
  scope :error,             ->           { where('warn IS false') }
  scope :by_category,       ->(category) { where(category: category)}
  scope :by_mode,           ->(mode)     { where(mode:     mode)}
  scope :by_parser,         ->(parser)   { where(parser:   parser)}

  def self.full_reprocess(error_class = nil)
    CSV.open("error_list.csv", "w", {headers: true, col_sep: ';', quote_char: '"'}) do |csv|
      csv << ['url', 'page', 'category']
      CsvError.all.each do |error|
        line     = error.source_line
        options  = Parsers::Fast.page_options(error.parser, nil)
        url      = eval(options[:url].strip)
        page     = error.parser
        category = error.category
        csv << [url, page, category]
      end
    end
  end

end

app/controllers/csv_errors_controller.rb
class CsvErrorsController < ApplicationController
  before_action :set_csv_error, only: [:show, :edit, :update, :destroy]

  # GET /csv_errors
  # GET /csv_errors.json
  def index
    @csv_errors = CsvError.all
  end

  # GET /csv_errors/1
  # GET /csv_errors/1.json
  def show
  end

  # GET /csv_errors/new
  def new
    @csv_error = CsvError.new
  end

  # GET /csv_errors/1/edit
  def edit
  end

  # POST /csv_errors
  # POST /csv_errors.json
  def create
    @csv_error = CsvError.new(csv_error_params)

    respond_to do |format|
      if @csv_error.save
        format.html { redirect_to @csv_error, notice: 'Csv error was successfully created.' }
        format.json { render :show, status: :created, location: @csv_error }
      else
        format.html { render :new }
        format.json { render json: @csv_error.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /csv_errors/1
  # PATCH/PUT /csv_errors/1.json
  def update
    respond_to do |format|
      if @csv_error.update(csv_error_params)
        format.html { redirect_to @csv_error, notice: 'Csv error was successfully updated.' }
        format.json { render :show, status: :ok, location: @csv_error }
      else
        format.html { render :edit }
        format.json { render json: @csv_error.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /csv_errors/1
  # DELETE /csv_errors/1.json
  def destroy
    @csv_error.destroy
    respond_to do |format|
      format.html { redirect_to csv_errors_url, notice: 'Csv error was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_csv_error
      @csv_error = CsvError.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def csv_error_params
      params.require(:csv_error).permit(:source_line, :error, :mode, :parser, :category, :warn)
    end
end

app/helpers/csv_errors_helper.rb
module CsvErrorsHelper
end

app/views/csv_errors/_form.html.haml
= form_for @csv_error do |f|
  - if @csv_error.errors.any?
    #error_explanation
      %h2= "#{pluralize(@csv_error.errors.count, "error")} prohibited this csv_error from being saved:"
      %ul
        - @csv_error.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :source_line
    = f.text_area :source_line
  .field
    = f.label :error
    = f.text_field :error
  .field
    = f.label :mode
    = f.text_field :mode
  .field
    = f.label :parser
    = f.text_field :parser
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :warn
    = f.check_box :warn
  .actions
    = f.submit 'Save'

app/views/csv_errors/edit.html.haml
%h1 Editing csv_error

= render 'form'

= link_to 'Show', @csv_error
\|
= link_to 'Back', csv_errors_path

app/views/csv_errors/index.html.haml
%h1 Listing csv_errors

%table
  %thead
    %tr
      %th Source line
      %th Error
      %th Mode
      %th Parser
      %th Category
      %th Warn
      %th
      %th
      %th

  %tbody
    - @csv_errors.each do |csv_error|
      %tr
        %td= csv_error.source_line
        %td= csv_error.error
        %td= csv_error.mode
        %td= csv_error.parser
        %td= csv_error.category
        %td= csv_error.warn
        %td= link_to 'Show', csv_error
        %td= link_to 'Edit', edit_csv_error_path(csv_error)
        %td= link_to 'Destroy', csv_error, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Csv error', new_csv_error_path

app/views/csv_errors/new.html.haml
%h1 New csv_error

= render 'form'

= link_to 'Back', csv_errors_path

app/views/csv_errors/show.html.haml
%p#notice= notice

%p
  %b Source line:
  = @csv_error.source_line
%p
  %b Error:
  = @csv_error.error
%p
  %b Mode:
  = @csv_error.mode
%p
  %b Parser:
  = @csv_error.parser
%p
  %b Category:
  = @csv_error.category
%p
  %b Warn:
  = @csv_error.warn

= link_to 'Edit', edit_csv_error_path(@csv_error)
\|
= link_to 'Back', csv_errors_path