config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  authenticated :user, -> user { user.admin? }  do
    mount DelayedJobWeb, at: "/delayed_job"
  end

  match "/admin/import_specs/change_subcategories" => 'admin/import_specs#change_subcategories',  via: :post
  match "/admin/import_specs/change_specs"         => 'admin/import_specs#change_specs',          via: :post
  match "/admin/import_specs/change_origin_specs"  => 'admin/import_specs#change_origin_specs',   via: :post
  match "/admin/import_specs/change_spec_examples" => 'admin/import_specs#change_spec_examples',  via: :post

  match "/admin/import_specs/:id/change_subcategories" => 'admin/import_specs#change_subcategories',  via: :post
  match "/admin/import_specs/:id/change_specs"         => 'admin/import_specs#change_specs',          via: :post
  match "/admin/import_specs/:id/change_origin_specs"  => 'admin/import_specs#change_origin_specs',   via: :post
  match "/admin/import_specs/:id/change_spec_examples" => 'admin/import_specs#change_spec_examples',  via: :post

  match "/admin/page_departments/url_example" => 'admin/page_departments#url_example',  via: :post
  match "/admin/page_departments/:id/url_example" => 'admin/page_departments#url_example',  via: :post

  devise_for :users

  resources :public do
    get 'products', on: :collection
  end
  resources :price_categories
  resources :csv_errors
  resources :products
  resources :files do
    post :upload, on: :collection
    get :send_daily_reports, on: :collection
    get :send_top_seller_report, on: :collection
  end

  match "benchmark"          => "benchmark#index", via: [:get, :post]
  match "benchmark/products" => "benchmark#products", via: :get
  match "map"                => "minimum_advertised_price#index", via: :get
  match "price_evolution"    => "price_evolution#index", via: [:get, :post]

  match "product_evolution"     => "product_evolution#index", via: :get
  match "product_evolution/:id" => "product_evolution#show", via: [:get, :post], as: :show_product_evolution

  root to: 'public#index'
end

app/controllers/benchmark_controller.rb
class BenchmarkController < ApplicationController
  include ActionView::Helpers::NumberHelper
  include SearchableActions
  include ParamsUtils
  include ApplicationHelper

  has_orders %w{name brand subcategory msrp }
  before_action :read_params

  def index
    prepare_data
    get_total_days
    respond_to do |format|
      format.html
      format.js { render 'global/index', locals: { index_folder: 'benchmark',
                                                   n_templates: 1,
                                                   templates: ['content'],
                                                   bind_elements: ['benchmark_content'],
                                                   title: @title}}
      format.xlsx { export_summary }
    end
  end

  def products
    @ecommerces = pages_to_show
    @product_ids = fetch_benchmark['product_ids']

    if get_total_days == 1
      products_one_day
    else
      products_range_days
    end
  end

  private
  def get_total_days
    @total_days ||= (@end_date == @start_date) ? 1 : (@end_date - @start_date).to_i
  end

  def resource_model
    Product
  end

  def products_one_day
    groups = ['products.id']
    select_string = "(ARRAY_AGG(product_pages.image_url))[1] AS image_url,
                     products.brand, products.name, products.subcategory, products.specs, products.msrp,
                     STRING_AGG(product_pages.page, ',') as pages,
                     STRING_AGG(product_prices.price::character varying, ',') as prices"

    @products = CalculationsHelper
                  .general_query(groups: groups, select_string: select_string,
                                 available: get_available, start_date: @start_date, end_date: @end_date,
                                 pages: @ecommerces.keys, brands: @default_brands, category: @category,
                                 subcategories: @subcategory || current_user.available_subcategories_for(@category),
                                 min_price: @min_price, max_price: @max_price, specs: @specs, models: @model)
                  .where('products.id' => @product_ids)
    SqlLog.debug("bechmark_products_one_day-------------------------------------------------------->\n")

    search_resources(paginated: params[:format] != 'xlsx')

    respond_to do |format|
      format.js { render :products_one_day, layout: false }
      format.xlsx { export_products_one_day }
    end
  end

  def products_range_days
    groups = ['products.id', 'product_pages.page']
    select_string = "products.brand, products.name, products.subcategory, products.specs, product_pages.page,
                     AVG(product_prices.price) as avg, MAX(product_prices.price) as max, MIN(product_prices.price) as min,
                     MIN(product_prices.date) as first_day, MAX(product_prices.date) as last_day"
    @products = CalculationsHelper
                  .general_query(groups: groups, select_string: select_string,
                                 available: get_available, start_date: @start_date, end_date: @end_date,
                                 pages: @ecommerces.keys, brands: @default_brands, category: @category,
                                 subcategories: @subcategory || current_user.available_subcategories_for(@category),
                                 min_price: @min_price, max_price: @max_price, specs: @specs, models: @model)
                  .where('products.id' => @product_ids)
    SqlLog.debug("bechmark_products_range_days ---------------------------------------------------->\n")

    search_resources(paginated: params[:format] != 'xlsx')

    respond_to do |format|
      format.js { render :products_range_days, layout: false }
      format.xlsx { export_products_range_days }
    end
  end

  def fetch_benchmark
    @default_markets = pages_to_show&.keys
    @default_brands = brands_to_show_filtered
    @markets = @default_markets.blank? ? nil: @default_markets
    @brands = @default_brands.blank? ? nil: @default_brands
    params.merge!({markets: @markets, brand: @brands})

    DataGroupedCalculation
      .new(@start_date, @end_date, current_user.society, {
        category: @category,
        subcategory: @subcategory,
        page: @default_markets,
        brand: @default_brands,
        listed: @filter,
        min_price: @min_price,
        max_price: @max_price,
        specs: @specs,
        models: @models
      }).fetch_benchmark
  end

  def prepare_data
    data = fetch_benchmark

    filter_pages(data)
    filter_brands(data, references: @default_brands)
    filter_subcategories(data, @category)

    get_total_days
    @benchmark = data['benchmark']
    @num_brands = @benchmark['brands'].keys.size
    @sort_class = @num_brands > 1 ? 'sort' : nil
  end

  # Called by read_params
  def get_title
    @title = "Benchmark Category Index: #{params[:category]}"
  end

  def products_params
    params.permit(:page, :order, :direction, :start_date, :end_date, :option, :category,
                  :min_price, :max_price, subcategory: [], markets: [], brand: [], model: [],
                  specs: Product.map_specs_keys[@category]&.keys&.map{|key| [key, []]}.to_h)
  end
  helper_method :products_params

  def available_days(total_days, first_day, last_day)
    interval = (last_day - first_day).to_i
    interval = 1 if interval == 0
    number_to_percentage((interval * 100)/total_days.to_f, precision: 0)
  end
  helper_method :available_days

  def export_summary
    workbook_name = "benchmark_#{@category.parameterize.underscore}_summary.xlsx"
    tmp = Tempfile.new(['chart', '.png'])
    Utils.convert_data_url_to_image(params[:data_url], tmp.path)
    Axlsx::Package.new do |p|
      p.workbook.add_worksheet(:name => 'Summary') do |sheet|
        sheet.add_row [@category,
                       I18n.t('benchmark.summary.skus'),
                       I18n.t('benchmark.summary.asp'),
                       I18n.t('benchmark.summary.offers'),
                       I18n.t('benchmark.summary.share'),
                       I18n.t('benchmark.summary.weight')], b: true
        if @benchmark['brands'].keys.size > 1
          sheet.add_row ['Average',
                         number_with_precision(@benchmark['average']['skus'], precision: 2),
                         number_with_precision(@benchmark['average']['asp'], precision: 0),
                         number_with_precision(@benchmark['average']['offers'], precision: 2), '---', '---'],
                        types: [:string, :float, :string, :float, :string] # :date, :time, :float, :integer, :string, :boolean
          sheet.rows.last.cells[0].b = true
        end
        @benchmark['brands'].keys.sort.each do |brand|
          sheet.add_row [brand,
                         @benchmark['brands'][brand]['skus'],
                         number_with_precision(@benchmark['brands'][brand]['asp'], precision: 0),
                         @benchmark['brands'][brand]['offers'],
                         (number_to_percentage(@benchmark['brands'][brand]['offers'] * 100.0 / @benchmark['summations']['total_offers'], precision: 2) rescue 0),
                         number_to_percentage(@benchmark['brands'][brand]['weight'], precision: 0)],
                        types: [:string, :integer, :string, :integer, :string] # :date, :time, :float, :integer, :string, :boolean
          sheet.rows.last.cells[0].b = true
        end
      end
      # Add chart
      p.workbook.add_worksheet(:name => I18n.t('benchmark.tabs.chart')) do |sheet|
        sheet.add_image(:image_src => tmp.path, :noSelect => true, :noMove => true) do |image|
          image.width = 1205
          image.height = 450
          image.start_at 0, 0
        end
        sheet.merge_cells("A1:Q19")
      end
      send_data p.to_stream.read,
                type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                filename: workbook_name
    end
  end

  def prices_one_day(product)
    @ecommerces.keys.map do |key|
      value = symmetrical_value(product.pages.split(','), product.prices.split(','), key)
      number_with_precision(value, precision: 0)
    end
  end

  def export_products_one_day
    workbook_name = "benchmark_#{@category.parameterize.underscore}_products_#{@start_date}.xlsx"
    head = [I18n.t('benchmark.products.brand'),
            I18n.t('benchmark.products.model'),
            I18n.t('benchmark.products.subcategory'),
            I18n.t('benchmark.products.specs'),
            I18n.t('benchmark.products.msrp')] + @ecommerces.keys.map{|key| @ecommerces[key]}
    Axlsx::Package.new do |p|
      p.use_shared_strings = true
      wrap = p.workbook.styles.add_style alignment: {wrap_text: true}
      p.workbook.add_worksheet(:name => 'Products (1 day)') do |sheet|
        sheet.add_row head, b: true
        @products.each do |product|
          sheet.add_row [product.brand, product.name, product.subcategory,
                         ActionView::Base.full_sanitizer.sanitize(pretty_print_json(product.specs, separator: "\r")),
                         number_with_precision(product.msrp, precision: 0), *prices_one_day(product)],
                        types: [:string] * head.size, # :date, :time, :float, :integer, :string, :boolean
                        style: wrap
          sheet.column_widths(*([nil] * 3 + [40] + [nil] * (@ecommerces.keys.size + 1)))
        end
      end

      send_data p.to_stream.read,
                type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                filename: workbook_name
    end
  end

  def export_products_range_days
    workbook_name = "benchmark_#{@category.parameterize.underscore}_products_#{@start_date}_#{@end_date}.xlsx"
    head = [I18n.t('benchmark.products.brand'),
            I18n.t('benchmark.products.model'),
            I18n.t('benchmark.products.subcategory'),
            I18n.t('benchmark.products.specs'),
            I18n.t('benchmark.products.ecommerce'),

app/helpers/benchmark_helper.rb
module BenchmarkHelper
  def bubble_chart(data_source, options = {})
    chartkick_chart "BubbleChart", data_source, options
  end
end

app/views/benchmark/_chart.html.erb
<%= render_chart(bubble_data(@benchmark), partial: 'global/charts/google_chart',
                 type: 'bubble', options: bubble_options(@benchmark),
                 title: "#{@category} benchmark chart".upcase,
                 h_axis_title: 'SKUs',
                 v_axis_title: 'ASP') if @benchmark['brands']%>

app/views/benchmark/_content.html.erb
<div class="m-content" id="benchmark_content">
  <%= show_current_filters %>
  <% if @warnings.blank? %>
    <%= render partial: 'chart' %>
    <%= render partial: 'tabs' %>
  <% else %>
    <%= render partial: 'global/warnings' %>
  <% end %>
</div>

app/views/benchmark/_summary.html.erb
<div class="x-table">
  <table data-gt="1" class="table table-hover table-bordered table-striped data-table fixed">
    <thead>
      <tr>
        <th class="<%=@sort_class%>"><%= @category %> <i></i></th>
        <th class="<%=@sort_class%>"><%=t('.skus')%> <i></i></th>
        <th class="<%=@sort_class%>"><%=t('.asp')%> <i></i></th>
        <th class="<%=@sort_class%>"><%=t('.offers')%> <i></i></th>
        <th class="<%=@sort_class%>"><%=t('.share')%> <i></i></th>
        <th class="<%=@sort_class%>"><%=t('.weight')%> <i></i></th>
      </tr>
      <% if @num_brands > 1 %>
      <tr>
        <td class="weight-600"><%=t('.average')%></td>
        <td class="weight-600"><%= number_with_precision(@benchmark['average']['skus'], precision: 2) %></td>
        <td class="weight-600"><%= basic_price(@benchmark['average']['asp']) %></td>
        <td class="weight-600"><%= number_with_precision(@benchmark['average']['offers'], precision: 2) %></td>
        <td class="weight-600"> --- </td>
        <td class="weight-600"> --- </td>
      </tr>
    <% end %>
    </thead>
    <tbody>
    <% @benchmark['brands'].keys.sort.each do |brand| %>
      <tr>
        <td><%= brand %></td>
        <td><%= @benchmark['brands'][brand]['skus'] %></td>
        <td><%= basic_price(@benchmark['brands'][brand]['asp']) %></td>
        <td><%= @benchmark['brands'][brand]['offers'] %></td>
        <td><%= number_to_percentage(@benchmark['brands'][brand]['offers'] * 100.0 / @benchmark['summations']['total_offers'], precision: 2)  rescue 0 %></td>
        <td><%= number_to_percentage(@benchmark['brands'][brand]['weight'], precision: 0) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <div class="text-right">
    <%= form_tag(benchmark_path, method: :post) do %>
      <% current_filters.each do |key, value| %>
        <% if value.is_a?(Array) %>
          <% value.each do |v| %>
            <%= hidden_field_tag("#{key}[]", v) %>
          <% end %>
        <% else %>
          <%= hidden_field_tag(key, value) %>
        <% end %>
      <% end %>
      <%= hidden_field_tag(:data_url) %>
      <%= hidden_field_tag(:format, :xlsx) %>
      <%= button_tag(type: 'submit', id: 'download_excel', class: "btn btn-default action-download") do %>
        <%=t('global.download_excel')%> <i class="la la-download"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/benchmark/_tabs.html.erb
<div class="mb-5 tabs-with-ajax" data-target="m_tabs_detail">
  <div class="m-portlet__body">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active show" id="tab_summary" data-toggle="tab" href="#m_tabs_summary"><%=t('.summary')%></a>
      </li>
      <li class="nav-item">
        <%= link_to(benchmark_products_path(products_params),
                    class: 'nav-link action-download', id: 'tab_detail',
                    data: {toggle: 'tabajax', target: '#m_tabs_detail', remote: true})  do %>
          <%= t('.tab_detail')%> <i class="la la-download" data-url="<%=benchmark_products_path(products_params.merge(format: :xlsx))%>"></i>
        <% end %>
      </li>
      <li class="nav-item">
        <a id='download_png' class="nav-link" href="#m_tabs_download" data-toggle="tab" title="<%=t('.download_chart')%>">
          <%=t('.chart')%> <i class="la la-download"></i>
        </a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active show" id="m_tabs_summary" role="tabpanel">
        <%= render partial: 'summary' %>
      </div>
      <div class="tab-pane" id="m_tabs_detail" role="tabpanel"></div>
      <div class="tab-pane" id="m_tabs_download" role="tabpanel">
        <div class="container-fluid">
          <div class="col-sm-12 col-md-8">
            <a href="#" download="chart.png" title="<%=t('.download_image')%>" onclick="$(this).attr('href', $('#content_img').attr('src'))">
              <%= image_tag('fallback/missing.png', id: :content_img, class: 'download-image border') %>
            </a>
            <div class="font-italic text-right"><%=t('.downloadable_image')%></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/benchmark/_vertical_menu.html.erb
<% content_for :basic_filters do %>
  <%= render partial: 'global/accordion_ecommerce',
             locals: {pages: @reference_pages.merge(@another_pages), type: 'checkbox'} %>
  <%= render partial: 'global/accordion_brand',
             locals: {references: @reference_brands, others: @another_brands, type: 'checkbox'} %>
  <%= render partial: 'global/accordion_subcategory', locals: {subcategories: @subcategories} %>
  <%= render partial: 'global/accordion_price' %>
  <%= render partial: 'global/accordion_model' %>
  <%= render partial: 'global/accordion_availability' %>
<% end %>

<% content_for :advanced_filters do %>
  <%= render partial: 'global/accordion_specs' %>
<% end %>

<form id="filters" class="sticked-vertical-menu">
  <% if current_user.has_filter_by_specs? %>
    <div class="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark "
         data-menu-vertical="true" data-menu-scrollable="false" data-menu-dropdown-timeout="500">
      <ul class="m-menu__nav m-menu__nav--dropdown-submenu-arrow ">
        <div class="m-menu__section-text form-check menu-filter-check" id="m_ver_menu" role="tablist">
          <div class="card">
            <div class="card-header main" role="tab" id="headingOne">
              <h4 class="mb-0 m-menu__section-text">
                <a href="#" class="filters-type" data-toggle="collapse" data-target="#basicFilters" aria-expanded="true" aria-controls="basicFilters">
                  <span class="indicator"></span> <%=t('global.basic_filters').upcase %>
                </a>
              </h4>
            </div>
            <div id="basicFilters" class="collapse show mb-3" aria-labelledby="headingOne" data-parent="#m_ver_menu">
              <%= content_for :basic_filters %>
            </div>
            <div class="card-header main" role="tab" id="headingTwo">
              <h4 class="mb-0 m-menu__section-text">
                <a href="#" class="filters-type" data-toggle="collapse" data-target="#advancedFilters" aria-expanded="false" aria-controls="advancedFilters">
                  <span class="indicator"></span> <%=t('global.advanced_filters').upcase %>
                  <small class="pl-4 text-muted text-nowrap"><%=t('global.filters_by_specs')%></small>
                </a>
              </h4>
            </div>
            <div id="advancedFilters" class="collapse filters" aria-labelledby="headingTwo" data-parent="#m_ver_menu">
              <%= content_for :advanced_filters %>
            </div>
          </div>
          <%= render partial: 'global/reset_button' %>
        </div>
      </ul>
    </div>
  <% else %>
    <div id="m_ver_menu" class="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark "
         data-menu-vertical="true" data-menu-scrollable="false" data-menu-dropdown-timeout="500">
      <ul class="m-menu__nav m-menu__nav--dropdown-submenu-arrow ">
        <%= content_for :basic_filters %>
        <%= render partial: 'global/reset_button' %>
      </ul>
    </div>
  <% end %>
</form>

app/views/benchmark/index.html.erb
<% content_for :vertical_menu, render(partial: 'vertical_menu') %>

<%= render(partial: 'global/subheader', locals: {title: @title, start_date: @start_date, end_date: @end_date}) %>

<%= render partial: 'content' %>

app/views/benchmark/products_one_day.html.erb
<%= page_entries_info @products if @products.empty? %>
<% unless @products.empty? %>
  <div class="x-table">
    <caption class="caption-top">
      <%= page_entries_info @products %>
    </caption>
    <div class="mt-2"></div>
    <table class="table table-hover table-bordered table-striped data-table fixed">
      <thead>
      <tr>
        <th class="text-center"><%=t('benchmark.products.picture')%></th>
        <th class="text-center"><%= sort_link 'brand', remote: true %></th>
        <th class="text-center"><%= sort_link 'name', remote: true %></th>
        <th class="text-center"><%= sort_link 'subcategory', remote: true %></th>
        <th class="text-center"><%=t('benchmark.products.specs')%></th>
        <th class="text-center"><%= sort_link 'msrp', remote: true %></th>
        <% @ecommerces.keys.each do |key| %>
          <th class="text-center"><%= @ecommerces[key] %></th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% @products.each do |product| %>
        <tr>
          <td>
            <%= link_to image_tag(ensure_image_url(product.image_url), alt: nil, title: product.name,
                                  class: 'frame-img missing_picture'),
                        ensure_image_url(product.image_url),
                        target: '_blank' %>
          </td>
          <td><%= product.brand %></td>
          <td><%= product.name %></td>
          <td><%= product.subcategory %></td>
          <td class="small col-width-16"><%= pretty_print_json(product.specs) %></td>
          <td class="text-nowrap text-center"><%= basic_price(product.msrp) %></td>
          <% @ecommerces.keys.each do |key| %>
            <td class="fix-width text-center"><%= basic_price(symmetrical_value(product.pages.split(','), product.prices.split(','), key)) %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="mb-5">
    <%= content_tag(:div, paginate(@products, remote: true, param_name: :sheet), class: 'float-left') %>  &nbsp;
    <%= link_to(benchmark_products_path(products_params.merge(format: :xlsx)), class: "btn float-right btn-default action-download") do %>
      <%=t('global.download_excel')%> <i class="la la-download"></i>
    <% end %>
  </div>
<% end %>

app/views/benchmark/products_range_days.html.erb
<%= page_entries_info @products if @products.empty? %>
<% unless @products.empty? %>
  <div class="x-table">
    <caption class="caption-top">
      <%= page_entries_info @products %>
    </caption>
    <div class="mt-2"></div>
    <table class="table table-hover table-bordered table-striped data-table fixed">
      <thead>
      <tr>
        <th class="text-center"><%= sort_link 'brand', remote: true %></th>
        <th class="text-center"><%= sort_link 'name', remote: true %></th>
        <th class="text-center"><%= sort_link 'subcategory', remote: true %></th>
        <th class="text-center"><%=t('benchmark.products.specs')%></th>
        <th class="text-center"><%=t('benchmark.products.ecommerce')%></th>
        <th class="text-center"><%=t('benchmark.products.asp')%></th>
        <th class="text-center"><%=t('benchmark.products.max_price')%></th>
        <th class="text-center"><%=t('benchmark.products.min_price')%></th>
        <th class="text-center"><%=t('benchmark.products.first_day')%></th>
        <th class="text-center"><%=t('benchmark.products.last_day')%></th>
        <th class="text-center"><%=t('benchmark.products.days_available')%></th>
      </tr>
      </thead>
      <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.brand %></td>
          <td><%= product.name %></td>
          <td><%= product.subcategory %></td>
          <td class="small col-width-16"><%= pretty_print_json(product.specs) %></td>
          <td><%= @ecommerces[product['page']] %></td>
          <td class="text-center text-nowrap"><%= basic_price product.avg %></td>
          <td class="text-center text-nowrap"><%= basic_price product.max %></td>
          <td class="text-center text-nowrap"><%= basic_price product.min %></td>
          <td><%= format_date product.first_day %></td>
          <td><%= format_date product.last_day %></td>
          <td class="text-center"><%= available_days(@total_days, product.first_day, product.last_day) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="mb-5">
    <%= content_tag(:div, paginate(@products, remote: true, param_name: :sheet), class: 'float-left') %>  &nbsp;
    <%= link_to(benchmark_products_path(products_params.merge(format: :xlsx)), class: "btn float-right btn-default action-download") do %>
      <%=t('global.download_excel')%> <i class="la la-download"></i>
    <% end %>
  </div>
<% end %>