config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  authenticated :user, -> user { user.admin? }  do
    mount DelayedJobWeb, at: "/delayed_job"
  end

  match "/admin/import_specs/change_subcategories" => 'admin/import_specs#change_subcategories',  via: :post
  match "/admin/import_specs/change_specs"         => 'admin/import_specs#change_specs',          via: :post
  match "/admin/import_specs/change_origin_specs"  => 'admin/import_specs#change_origin_specs',   via: :post
  match "/admin/import_specs/change_spec_examples" => 'admin/import_specs#change_spec_examples',  via: :post

  match "/admin/import_specs/:id/change_subcategories" => 'admin/import_specs#change_subcategories',  via: :post
  match "/admin/import_specs/:id/change_specs"         => 'admin/import_specs#change_specs',          via: :post
  match "/admin/import_specs/:id/change_origin_specs"  => 'admin/import_specs#change_origin_specs',   via: :post
  match "/admin/import_specs/:id/change_spec_examples" => 'admin/import_specs#change_spec_examples',  via: :post

  match "/admin/page_departments/url_example" => 'admin/page_departments#url_example',  via: :post
  match "/admin/page_departments/:id/url_example" => 'admin/page_departments#url_example',  via: :post

  devise_for :users

  resources :public do
    get 'products', on: :collection
  end
  resources :price_categories
  resources :csv_errors
  resources :products
  resources :files do
    post :upload, on: :collection
    get :send_daily_reports, on: :collection
    get :send_top_seller_report, on: :collection
  end

  match "benchmark"          => "benchmark#index", via: [:get, :post]
  match "benchmark/products" => "benchmark#products", via: :get
  match "map"                => "minimum_advertised_price#index", via: :get
  match "price_evolution"    => "price_evolution#index", via: [:get, :post]

  match "product_evolution"     => "product_evolution#index", via: :get
  match "product_evolution/:id" => "product_evolution#show", via: [:get, :post], as: :show_product_evolution

  root to: 'public#index'
end

app/controllers/product_evolution_controller.rb
class ProductEvolutionController < ApplicationController
  include ActionView::Helpers::NumberHelper
  include SearchableActions
  include ParamsUtils
  include ApplicationHelper

  has_orders %w{_brand _name _category _subcategory _previous_price _price _variance _variance_percent _page _date}
  before_action :read_params

  def index
    @products = products_list

    search_resources(paginated: params[:format] != 'xlsx')

    respond_to do |format|
      format.html { render :index, layout: !helpers.is_popup_or_request_xhr? }
      format.js {
        render 'global/index', locals: {
          index_folder: 'product_evolution',
          templates: ['products_list'],
          bind_elements: ['paginated-dialog'],
          title: @title
        }
      }
      format.xlsx { export_products_index }
    end
  end

  def show
    data = fetch_dashboard
    prepare_data(data)
    start_date = @start_date.yesterday
    @title = 'Product Price Evolution'

    select1 = 'products.id AS product_id, product_pages.page, product_prices.product_page_id, ' +
              'product_prices.price, product_prices.date, LAG(price, 1, 0::double precision) ' +
              'OVER (PARTITION BY product_page_id ORDER BY product_page_id, product_prices.date ASC) AS previous_price'

    products = CalculationsHelper.general_query(
      groups: [], select_string: select1,
      available: get_available, start_date: start_date, end_date: @end_date,
      pages: @markets, brands: @brands, category: nil, subcategories: nil,
      min_price: 0, max_price: CalculationsHelper::MAX_PRICE, specs: nil, models: nil
    ).where('products.id' => params[:id])

    @prices = ProductPrice.select('DISTINCT ON (first_query.page, first_query.date) first_query.*')
      .from("(#{products.to_sql}) AS first_query")
      .reorder('page, date, price ASC')

    prepare_data_for_show

    respond_to do |format|
      format.html { render :show }
      format.js {
        render 'global/index', locals: {
          index_folder: 'product_evolution',
          templates: ['product_details'],
          bind_elements: ['product_evolution_detail'],
          title: @title
        }
      }
      format.xlsx { export_product }
    end
  end

  private

  def products_list
    data = fetch_dashboard
    prepare_data(data)
    product_ids = data['categories'].map(&:last)
      .reduce([]) { |ids, cat| ids += cat['products_prices_changed_ids'] || [] }

    return Product.none if product_ids.blank?

    start_date = @start_date.yesterday
    lag = 'LAG(price, 1, 0::double precision) OVER (PARTITION BY product_id, product_page_id ' +
          'ORDER BY product_id, product_page_id, product_prices.date asc)'
    select1 = 'products.id AS product_id, products.brand, products.name, products.category, products.subcategory, ' +
            'product_pages.page, product_prices.product_page_id, product_prices.price, product_prices.date, ' +
            "#{lag} AS previous_price, price - #{lag} AS variance, (price - #{lag}) / NULLIF(#{lag},0) * 100 AS variance_percent"

    products = CalculationsHelper.general_query(
      groups: [], select_string: select1,
      available: get_available, start_date: start_date, end_date: @end_date,
      pages: @markets, brands: @brands, category: nil, subcategories: nil,
      min_price: 0, max_price: CalculationsHelper::MAX_PRICE, specs: nil, models: params['model']
    ).where('products.id' => product_ids)

    subquery = ProductPrice.select('DISTINCT ON (first_query.page, first_query.date) first_query.*')
      .from("(#{products.to_sql}) AS first_query")
      .where('variance <> 0 AND previous_price <> 0')
      .reorder('page, date, price ASC')

    results = ProductPrice.select('subquery.*')
      .from("(#{subquery.to_sql}) AS subquery")
      .reorder('')

    @num_products = results.count

    SqlLog.debug("PRODUCTS: #{product_ids}")
    SqlLog.debug("get_products_prices_changed ------------------------------------->\n #{results.to_sql}")

    results
  end

  def export_products_index
    @products = @products.includes(:product_page, :product).to_a
    Axlsx::Package.new do |p|
      p.workbook.add_worksheet(name: I18n.t('product_evolution.index.title')) do |p|
        header = [
          I18n.t('activerecord.attributes.product.brand'),
          I18n.t('activerecord.attributes.product.name'),
          I18n.t('activerecord.attributes.product.category'),
          I18n.t('activerecord.attributes.product.subcategory'),
          I18n.t('activerecord.attributes.product.previous_price'),
          I18n.t('activerecord.attributes.product.last_price'),
          I18n.t('activerecord.attributes.product.trend'),
          I18n.t('activerecord.attributes.product.variance_price'),
          I18n.t('activerecord.attributes.product.variance'),
          I18n.t('activerecord.attributes.product.page'),
          I18n.t('activerecord.attributes.product.date')
        ]
        p.add_row header, b: true

        types = [:string, :string, :string, :string, :float, :float, :string, :float, :float, :string, :date]
        @products.each do |product_price|
          row = [
            product_price['brand'],
            product_price['name'],
            product_price['category'],
            product_price['subcategory'],
            basic_price(product_price['previous_price'], precision: 2),
            basic_price(product_price['price'], precision: 2),
            I18n.t("public.products.#{product_price['variance'] > 0 ? 'raise' : 'lower'}"),
            product_price['variance'],
            product_price['variance_percent'],
            Ecommerce.map_ecommerce_name[product_price.page],
            product_price.date
          ]
          p.add_row row, types: types
        end
      end
      send_data p.to_stream.read,
                type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                filename: "#{I18n.t('product_evolution.index.title').parameterize.underscore}.xlsx"
    end
  end

  def export_product
    pages = @prices.group_by(&:product_page_id).map { |e| [e.first, e.last.first.page] }

    Axlsx::Package.new do |p|
      p.workbook.add_worksheet(name: I18n.t('product_evolution.index.title')) do |p|
        header = pages.reduce([I18n.t('activerecord.attributes.product.date')]) do |header, page|
          header << Ecommerce.map_ecommerce_name[page.last]
        end
        p.add_row header, b: true

        types = Array.new(header.size, :float)
        types[0] = :date

        @prices.group_by(&:date).each do |date, prices|
          row = [date]
          row = pages.reduce([date]) do |row, page|
            row << prices.find { |e| e.product_page_id == page.first }&.price
          end
          p.add_row row, types: types
        end
      end

      send_data p.to_stream.read,
                type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                filename: "#{I18n.t('product_evolution.show.title', product: @product.name).parameterize.underscore}.xlsx"
    end
  end

  def prepare_data_for_show
    @product = @prices&.first&.product
    @default_markets = pages_to_show&.keys
    @markets = @default_markets.blank? ? nil : @default_markets

    data = { 'markets' => Hash.new(0) }
    data['markets'] = ProductPrice.select('page, COUNT(page)')
      .from("(#{@prices.to_sql}) AS counter GROUP BY page")
      .reorder('')
      .reduce({}) { |h,p| h.update(p['page'] => p['count']) }

    filter_pages(data)
  end

  def prepare_data(data)
    filter_pages(data)
    filter_brands(data)

    @values = current_user.available_root_categories.inject({}) do |values, category|
      results = []
      %w( period_average average_percentage previous_period_average
          products_prices_up products_prices_down
          availables offered new_products disappeared_products products_in_stock
          availables_filtered offered_filtered
          products_prices_up_percentage products_prices_down_percentage).each do |field|
        # Fit array with info
        if field != 'products_in_stock'
          results << data['categories'][category.to_s][field]
        else
          results << data['categories'][category.to_s]['subcategories']['']['products_in_stock']
        end
      end
      values.merge(category => results)
    end

    without_data = @values.collect do |_key, values|
      values.all?{|value| value == 0}
    end

    @warning_message = I18n.t('global.period_without_data') if without_data.all?
    @page_name = pages_names[@markets]

    SqlLog.debug("prepare_data: ---------------------------->\n#{@values}")
  end

  def fetch_dashboard(force: false)
    @default_markets = pages_to_show.keys
    @default_brands = brands_to_show_filtered
    @markets = @default_markets.presence
    @brands = @default_brands.presence
    params.merge!({ page: @markets, brand: @brands })

    DataGroupedCalculation.new(@start_date, @end_date, current_user.society, {
      categories: @category,
      page: @markets,
      brand: @brands,
      listed: @filter
    }).fetch_dashboard(force)
  end

  def resource_model
    Product
  end

  def get_title
    @title = I18n.t('product_evolution.index.title')
  end
end

app/helpers/product_evolution_helper.rb
module ProductEvolutionHelper
  def is_popup?
    @mode == PublicController::POPUP
  end

  def is_popup_or_request_xhr?
    is_popup? || request.xhr?
  end
end

app/views/product_evolution/_chart.html.erb
<%= render_chart(product_evolution_data(@prices), partial: 'global/charts/google_chart_with_dashboard',
                 type: 'line', options: product_evolution_options(@prices),
                title: t('.product_trends', product: @prices.first.product.name),
                h_axis_title: t('.date'),
                v_axis_title: t('.price')) %>
<div id="tooltip_action"></div>

app/views/product_evolution/_product_details.html.erb
<div class="m-content" id="product_evolution_detail">
  <%= show_current_filters %>
  <% if @prices.present? %>
    <div class="row" style="padding-left: 130px">
      <div class="col-xs-6">
        <% img_url = @prices.uniq { |e| e.product_page_id }.select { |e| e.product_page.image_url.present? }.first.product_page.image_url %>
        <% img_tag = image_tag(ensure_image_url(img_url), alt: nil, title: @product.name, class: 'missing_picture', style: 'max-width: 300px; margin-right: 20px') %>
        <%= link_to img_tag, ensure_image_url(img_url), target: '_blank' %>
      </div>
      <div class="col-xs-6" style="padding-top: 25px; padding-bottom: 25px">
        <span class="font-weight-bold"><%= @product.brand %></span><br>
        <span class="font-weight-bold"><%= @product.name %></span><br>
        Subcategory: <span class="font-weight-bold"><%= @product.subcategory %></span><br>

        <%= t 'activerecord.attributes.product.first_day' %>: <span class="font-weight-bold"><%= l @product.created_at.to_date, format: :long %></span><br>
        <%= t '.min_price' %>: <span class="font-weight-bold"><%= @prices.min { |a, span| a.price <=> span.price }.price %></span><br>
        <%= t '.max_price' %>: <span class="font-weight-bold"><%= @prices.max { |a, span| a.price <=> span.price }.price %></span><br>
        <%= "#{t('.msrp')}: <span class=\"font-weight-bold\">#{@product.msrp}</span>".html_safe if @product.msrp.present? %>
      </div>
    </div>

    <% if @warnings.blank? || (@warnings - [:brands]).blank? %>
      <%= render partial: 'chart' %>
      <%= render partial: 'tabs' %>
    <% else %>
      <%= render partial: 'global/warnings' %>
    <% end %>
  <% else %>
    <%= t 'helpers.page_entries_info.one_page.display_entries.zero', entry_name: t('.products').downcase %>
  <% end %>
</div>

app/views/product_evolution/_products_list.html.erb
<div id="paginated-dialog" class="dialog-with-ajax" data-target="paginated-dialog">
  <%= show_current_filters %>
  <caption class="caption-top">
    <%= page_entries_info @products, entry_name: t('global.offer').downcase %>
  </caption>
  <% if @products.size > 0 %>
    <div class="x-table">
      <div class="mt-2"></div>
      <table class="table table-hover table-bordered table-striped data-table <%='fixed' unless is_popup? %>">
        <thead>
          <tr>
            <th><%= sort_link '_brand', title: t('activerecord.attributes.product.brand'), remote: true %></th>
            <th><%= sort_link '_name', title: t('activerecord.attributes.product.name'), remote: true %></th>
            <th><%= sort_link '_category', title: t('activerecord.attributes.product.category'), remote: true %></th>
            <th><%= sort_link '_subcategory', title: t('activerecord.attributes.product.subcategory'), remote: true %></th>
            <th><%= sort_link '_previous_price', title: t('activerecord.attributes.product.previous_price'), remote: true %></th>
            <th><%= sort_link '_price', title: t('activerecord.attributes.product.last_price'), remote: true %></th>
            <th><%= sort_link '_variance', title: t('activerecord.attributes.product.trend'), remote: true %></th>
            <th><%= sort_link '_variance', title: t('activerecord.attributes.product.variance_price'), remote: true %></th>
            <th><%= sort_link '_variance_percent', title: t('activerecord.attributes.product.variance'), remote: true %></th>
            <th><%= sort_link '_page', title: t('activerecord.attributes.product.page'), remote: true %></th>
            <th><%= sort_link '_date', title: t('activerecord.attributes.product.date'), remote: true %></th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product_price| %>
            <tr>
              <td><%= product_price['brand'] %></td>
              <td class="break-word"><%= link_to product_price['name'], show_product_evolution_path(product_price['product_id']) %></td>
              <td class="break-word"><%= product_price['category'] %></td>
              <td class="break-word"><%= product_price['subcategory'] %></td>
              <td class="text-nowrap"><%= basic_price(product_price['previous_price'], precision: 2) %></td>
              <td class="text-nowrap"><%= basic_price(product_price.price, precision: 2) %></td>
              <td><%= I18n.t("public.products.#{product_price['variance'] > 0 ? 'raise' : 'lower'}") %></td>
              <td><%= sprintf('%.2f', product_price['variance']) %></td>
              <td><%= number_to_percentage(product_price['variance_percent'], precision: 2) %></td>
              <td><%= Ecommerce.map_ecommerce_name[product_price['page']] %></td>
              <td><%= product_price.date %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="mb-5">
      <%= content_tag(:div, paginate(@products, params: { format: :html }, remote: true, window: 2, param_name: :sheet), class: 'float-left') %>
      <%= link_to(product_evolution_path(current_filters.merge(format: :xlsx)), class: "btn float-right btn-default action-download") do %>
        <%=t('global.download_excel')%> <i class="la la-download"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/product_evolution/_summary.html.erb
<% pages = @prices.group_by(&:product_page_id).map { |e| [e.first, e.last.first.page] }.sort_by { |e| e.last } %>

<div class="x-table">
  <table data-gt="1" class="table table-hover table-bordered table-striped data-table fixed">
    <thead>
      <tr>
        <th><%=t('.date')%></th>
        <% pages.each do |page| %>
          <th><%= Ecommerce.map_ecommerce_name[page.last] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% (@start_date..@prices.map(&:date).uniq.sort.last).each do |date| %>
      <% prices = @prices.select { |price| price.date == date }  %>
        <% next if prices.blank? %>
        <tr>
          <th><%= date %></th>
          <% pages.each do |page| %>
            <% product_price = prices.find { |e| e.product_page_id == page.first } %>
            <% if product_price.blank? %>
              <td></td>
            <% else %>
              <td class="text-center align-middle <%= level_by_variance(product_price['previous_price'], product_price.price) %>">
                <%= basic_price(product_price.price, precision: 2) %>
              </td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-right">
    <%= form_tag(show_product_evolution_path, method: :post) do %>
      <% current_filters.each do |key, value| %>
        <% if value.is_a?(Array) %>
          <% value.each do |v| %>
            <%= hidden_field_tag("#{key}[]", v) %>
          <% end %>
        <% else %>
          <%= hidden_field_tag(key, value) %>
        <% end %>
      <% end %>
      <%= hidden_field_tag(:data_url) %>
      <%= hidden_field_tag(:format, :xlsx) %>
      <%= button_tag(type: 'submit', id: 'download_excel', class: "btn btn-default action-download") do %>
        <%=t('global.download_excel')%> <i class="la la-download"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/product_evolution/_tabs.html.erb
<div class="mb-5 tabs-with-ajax" data-target="m_tabs_detail">
  <div class="m-portlet__body">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active show" id="tab_summary" data-toggle="tab" href="#m_tabs_summary"><%=t('.summary')%></a>
      </li>
      <li class="nav-item">
        <a id='download_png' class="nav-link" href="#m_tabs_download" data-toggle="tab" title="<%=t('.download_chart')%>">
          <%=t('.chart')%> <i class="la la-download"></i>
        </a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active show" id="m_tabs_summary" role="tabpanel">
        <%= render partial: 'summary' %>
      </div>
      <div class="tab-pane" id="m_tabs_detail" role="tabpanel"></div>
      <div class="tab-pane" id="m_tabs_download" role="tabpanel">
        <div class="container-fluid">
          <div class="col-sm-12 col-md-8">
            <a href="#" download="chart.png" title="<%=t('.download_image')%>" onclick="$(this).attr('href', $('#content_img').attr('src'))">
              <%= image_tag('fallback/missing.png', id: :content_img, class: 'download-image border') %>
            </a>
            <div class="font-italic text-right"><%=t('.downloadable_image')%></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/product_evolution/_vertical_menu.html.erb
<% content_for :basic_filters do %>
  <%= render partial: 'global/accordion_ecommerce',
             locals: { pages: @reference_pages.merge(@another_pages), type: 'checkbox' } %>

  <%= render partial: 'global/accordion_brand',
             locals: { references: @reference_brands, others: @another_brands, type: 'checkbox' } %>

  <%= render partial: 'global/accordion_model' %>
<% end %>

<form id="filters" class="sticked-vertical-menu">
  <div id="m_ver_menu" class="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark "
       data-menu-vertical="true" data-menu-scrollable="false" data-menu-dropdown-timeout="500">
    <ul class="m-menu__nav m-menu__nav--dropdown-submenu-arrow ">
      <%= content_for :basic_filters %>
      <%= render partial: 'global/reset_button' %>
    </ul>
  </div>
</form>

app/views/product_evolution/index.html.erb
<% unless is_popup_or_request_xhr? %>
<% content_for :vertical_menu, render(partial: 'vertical_menu') %>

<%= render partial: 'global/subheader', locals: { title: @title, start_date: @start_date, end_date: @end_date } %>
<% end %>

<% if is_popup_or_request_xhr? %>
  <%= render 'products_list' %>
<% else %>
  <div class="m-content" id="product_evolution">
    <%= render 'products_list' %>
  </div>
<% end %>

app/views/product_evolution/show.html.erb
<% @override_view_id = 'product_evolution_detail' %>
<div id="product_id" class="<%= params[:id] %>"></div>
<% content_for :vertical_menu do %>
  <div id="m_ver_menu" class="sticked-vertical-menu m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark"
       data-menu-vertical="true" data-menu-scrollable="false" data-menu-dropdown-timeout="500">
    <form id="filters">
      <ul class="m-menu__nav  m-menu__nav--dropdown-submenu-arrow ">
        <%= render partial: 'global/accordion_ecommerce',
                   locals: { pages: @reference_pages.merge(@another_pages), type: 'checkbox' } %>
        <%= render partial: 'global/reset_button' %>
      </ul>
    </form>
  </div>
<% end %>

<%= render 'global/subheader', title: @title, start_date: @start_date, end_date: @end_date %>

<%= render 'product_details', product: @product, prices: @prices %>