config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  authenticated :user, -> user { user.admin? }  do
    mount DelayedJobWeb, at: "/delayed_job"
  end

  match "/admin/import_specs/change_subcategories" => 'admin/import_specs#change_subcategories',  via: :post
  match "/admin/import_specs/change_specs"         => 'admin/import_specs#change_specs',          via: :post
  match "/admin/import_specs/change_origin_specs"  => 'admin/import_specs#change_origin_specs',   via: :post
  match "/admin/import_specs/change_spec_examples" => 'admin/import_specs#change_spec_examples',  via: :post

  match "/admin/import_specs/:id/change_subcategories" => 'admin/import_specs#change_subcategories',  via: :post
  match "/admin/import_specs/:id/change_specs"         => 'admin/import_specs#change_specs',          via: :post
  match "/admin/import_specs/:id/change_origin_specs"  => 'admin/import_specs#change_origin_specs',   via: :post
  match "/admin/import_specs/:id/change_spec_examples" => 'admin/import_specs#change_spec_examples',  via: :post

  match "/admin/page_departments/url_example" => 'admin/page_departments#url_example',  via: :post
  match "/admin/page_departments/:id/url_example" => 'admin/page_departments#url_example',  via: :post

  devise_for :users

  resources :public do
    get 'products', on: :collection
  end
  resources :price_categories
  resources :csv_errors
  resources :products
  resources :files do
    post :upload, on: :collection
    get :send_daily_reports, on: :collection
    get :send_top_seller_report, on: :collection
  end

  match "benchmark"          => "benchmark#index", via: [:get, :post]
  match "benchmark/products" => "benchmark#products", via: :get
  match "map"                => "minimum_advertised_price#index", via: :get
  match "price_evolution"    => "price_evolution#index", via: [:get, :post]

  match "product_evolution"     => "product_evolution#index", via: :get
  match "product_evolution/:id" => "product_evolution#show", via: [:get, :post], as: :show_product_evolution

  root to: 'public#index'
end

app/views/global/_accordion_availability.html.erb
<!-- Accordion Availability -->
<div class="m-menu__section-text form-check menu-filter-check" id="accordion3" role="tablist">
  <div class="card">
    <div class="card-header" role="tab" id="headingThree">
      <h4 class="mb-0 m-menu__section-text">
        <a class="m-menu__section-text-a" data-toggle="collapse" href="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
          Avaliability vs Listed
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="collapse show" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion3">
      <div class="card-body">
        <div class="" data-code-preview="true" data-code-html="true" data-code-js="false">
          <div class="">
            <div class="btn-group" data-toggle="buttons">
              <label class="btn m-btn--pill btn-pillradio-stramina <%= 'active' if params[:option].blank? || params[:option] == 'Available' %>" id="available">
                <input type="radio" name="options3" id="optionAvailable" autocomplete="off" <%= 'checked' if params[:option].blank? || params[:option] == 'Available' %> value="Available">
                Available
              </label>
              <label class="btn m-btn--pill btn-pillradio-stramina <%= 'active' if params[:option] == 'Listed' %>" id="listed">
                <input type="radio" name="options3" id="optionListed" autocomplete="off" <%= 'checked' if params[:option] == 'Listed' %> value="Listed">
                Listed
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/global/_accordion_brand.html.erb
<!-- Accordion brand -->
<div class="m-menu__section-text form-check menu-filter-check" id="accordion2" role="tablist">
  <div class="card">
    <div class="card-header" role="tab" id="headingTwo">
      <h4 class="mb-0 m-menu__section-text">
        <a data-toggle="collapse" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <%= t('global.brands')%>
        </a>
      </h4>
    </div>

    <span class="show-filters uncheck-element fa fa-eye" title="<%=t('global.show_filters')%>"
          data-ref="#collapseTwo label" data-filter-type="brand"></span>

    <span class="remove-all uncheck-element fa fa-trash" title="<%=t('global.clean_filters')%>"
          data-ref="#collapseTwo input:checked" data-apply-at-the-end="true"></span>

    <span class="reset-brands uncheck-element fa fa-check" title="<%=t('global.clean_filters')%>"></span>

    <div id="collapseTwo" class="collapse show" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion2">
      <div class="card-body">
        <div class="small my-2 text-warning hide" id="no-brands">
          <span class="fa fa-warning"></span> <%=t('global.no_brands')%>
        </div>
        <div id="displayedBrands">
          <% unless references.blank? %>
            <% references.keys.each do |key| %>
              <label class="form-check-label m-<%=type%> <%='hide' if references[key] == 0 %>">
                <input type="<%=type%>" name="options" id="<%= Utils.hashcode('brand', key) %>" autocomplete="off" <%= print_checked?(:brand, key) %> class="form-check-input" value="<%= key %>">
                <%= key %>
                <span></span>
                <div class="m-badge m-badge--success m-badge--wide" id="brand-<%= key.parameterize %>">
                  <%= references[key] %>
                </div>
              </label>
            <% end %>
          <% end %>
        </div>
        <% unless others.blank? %>
          <div class="card-body" id="accordion21">
            <div class="panel">
              <div id="collapseTwoOne" class="panel-collapse collapse">
                <% others.keys.each do |key| %>
                  <%= tag.label class: "form-check-label m-#{type} #{'hide' if others[key] == 0}" do %>
                    <input type="<%=type%>" name="options" id="<%= Utils.hashcode('brand', key) %>" autocomplete="off" <%= print_checked?(:brand, key) %> class="form-check-input" value="<%= key %>">
                    <%= key %>
                    <span></span>
                    <div class="m-badge m-badge--success m-badge--wide" id="brand-<%= key.parameterize %>">
                      <%= others[key] %>
                    </div>
                  <% end %>
                <% end %>
              </div>
              <a data-toggle="collapse" data-parent="#accordion21" href="#collapseTwoOne" class="seebutton"><%= t('global.see_all')%></a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/global/_accordion_model.html.erb
<!-- Accordion Model -->
<div class="m-menu__section-text form-check menu-filter-check" id="accordionModel" role="tablist">
  <div class="card">
    <div class="card-header" role="tab" id="headingModel">
      <h4 class="mb-0 m-menu__section-text">
        <a class="m-menu__section-text-a" data-toggle="collapse" href="#collapseModels" aria-expanded="true" aria-controls="collapseModels">
          <%=t('global.model')%>
        </a>
      </h4>
    </div>
    <div id="collapseModels" class="collapse filters show" role="tabpanel" aria-labelledby="headingModel" data-parent="#accordionModel">
      <div class="card-body">
        <%= select_tag("models", nil, multiple: true, class: 'models-data-ajax') %>
        <small class="search-button cursor-pointer text-white float-right mt-2"><%=t('global.apply')%></small>
      </div>
    </div>
  </div>
</div>

app/views/global/_accordion_price.html.erb
<!-- Accordion Price -->
<div class="m-menu__section-text form-check menu-filter-check" id="accordion4" role="tablist">
  <div class="card">
    <div class="card-header" role="tab" id="headingFour">
      <h4 class="mb-0 m-menu__section-text">
        <a class="m-menu__section-text-a" data-toggle="collapse" href="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
          <%=t('global.price')%>
        </a>
      </h4>
    </div>
    <span class="remove-all uncheck-element fa fa-trash" title="<%=t('global.clean_filters')%>"
          data-ref="#collapseFour input" data-apply-at-the-end="true"></span>
    <div id="collapseFour" class="collapse show" role="tabpanel" aria-labelledby="headingFour" data-parent="#accordion4">
      <div class="card-body">
        <input type="number" min="0" max="60000" placeholder="min" name="min_price" id="min_price" class="price-range very-small">
        <span class="text-white">-</span>
        <input type="number" min="0" max="60000" placeholder="max" name="max_price" id="max_price" class="price-range very-small">
        <small class="search-button cursor-pointer text-white ml-2"><%=t('global.apply')%></small>
      </div>
    </div>
  </div>
</div>

app/views/global/_accordion_specs.html.erb
<!-- Accordion specs -->
<% if Product.available_filters_in_specs[@category].nil? %>
  <div class="card">
    <div class="card-header">
      <div class="mb-0 text-warning">
        <span class="fa fa-warning"></span> <%=t('global.no_filters')%>
      </div>
    </div>
  </div>
<% else %>
  <% Product.available_filters_in_specs[@category].keys.each do |key| %>
    <%
      key_ref = key.parameterize(separator: '_')
      num_options = Product.available_filters_in_specs[@category][key].size
      is_expanded = num_options < 6 || num_options > 12
    %>
    <div class="m-menu__section-text form-check menu-filter-check" id="accordion_<%=key_ref%>" role="tablist">
      <div class="card">
        <div class="<%= is_expanded ? 'card-header' : 'card-header-click'%>" role="tab" id="heading_<%=key_ref%>">
          <h4 class="mb-0 m-menu__section-text">
            <a data-toggle="collapse" href="#collapse_<%=key_ref%>" aria-expanded="<%=is_expanded%>"
               title="<%=key.titleize%>" aria-controls="collapse_<%=key_ref%>">
              <%= truncate(key.titleize, length: 24) %>
            </a>
          </h4>
        </div>
        <% if num_options <= 12 %>
          <span class="remove-all specs uncheck-element fa fa-trash" title="<%=t('global.clean_filters')%>"
                data-ref="#collapse_<%=key_ref%> input:checked" data-apply-at-the-end="true"></span>
        <% end %>
        <div id="collapse_<%=key_ref%>" class="collapse <%='show' if is_expanded %>" role="tabpanel"
             aria-labelledby="heading_<%=key_ref%>" data-parent="#accordion_<%=key_ref%>">
          <div class="card-body">
            <% if num_options > 12 %>
              <% options = remove_zeros_options(Product.available_filters_in_specs[@category][key], @category) %>
              <%= select_tag("specs[#{key_ref}]",
                             options_for_select(options),
                             multiple: true, class: 'selectTwo') %>
            <% else %>
              <% Product.available_filters_in_specs[@category][key].each do |value| %>
                <label class="form-check-label m-checkbox">
                  <input type="checkbox" name="specs[<%=key_ref%>]" id="<%= Utils.hashcode("spec-#{@category}", value) %>" class="form-check-input" value="<%= value %>">
                  <%= remove_zero_decimals(value) %>
                  <span></span>
                </label>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/global/_accordion_subcategory.html.erb
<!-- Accordion Subcategories -->
<div class="m-menu__section-text form-check menu-filter-check" id="accordion5" role="tablist">
  <div class="card">
    <div class="card-header" role="tab" id="headingFive">
      <h4 class="mb-0 m-menu__section-text">
        <a data-toggle="collapse" href="#collapseFive" aria-expanded="true" aria-controls="collapseFive">
          <%= t('global.subcategory')%>
        </a>
      </h4>
    </div>
    <span class="show-filters uncheck-element fa fa-eye" title="<%=t('global.show_filters')%>"
          data-ref="#collapseFive label" data-filter-type="subcategory"></span>
    <span class="remove-all uncheck-element fa fa-trash" title="<%=t('global.clean_filters')%>"
          data-ref="#collapseFive input:checked" data-apply-at-the-end="true"></span>
    <div id="collapseFive" class="collapse show m-checkbox-list" role="tabpanel" aria-labelledby="headingFive" data-parent="#accordion5">
      <div class="card-body">
        <% unless subcategories.blank? %>
          <% subcategories.each do |_category, values| %>
            <div>
            <% if subcategories.keys.size > 1 %>
              <label class="label-left"><%= _category %></label>
            <% end %>
            <% values.each_with_index do |subcategory, index| %>
              <% next if subcategory[0].blank? %>
              <label class="form-check-label m-checkbox">
                <input type="checkbox" name="options" id="<%= Utils.hashcode('subcategory', _category, subcategory[0]) %>" autocomplete="off" class="form-check-input" value="<%= subcategory[0] %>">
                <%= subcategory[0] %>
                <span></span>
                <div class="m-badge m-badge--success m-badge--wide" id="subcategory-<%= _category.parameterize %>-<%= subcategory[0].parameterize %>">
                  <%= subcategory[1] %>
                </div>
              </label>
            <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/global/_colors_table.html.erb
<!-- Legend of table -->
<div class="legend float-left">
  <table class="legend-table">
    <tbody>
    <tr>
      <td class="legendColorBox">
        <div class="legendColorBox-inside">
          <div class="legendBox-inner" style="border:6px solid #d4888a;">
          </div>
        </div>
      </td>
      <td class="legendLabel"> &lt;&nbsp; -20% </td>
      <td class="legendColorBox">
        <div class="legendColorBox-inside">
          <div class="legendBox-inner" style="border:6px solid #ebb3b4;">
          </div>
        </div>
      </td>
      <td class="legendLabel" > -20% - -10%</td>
      <td class="legendColorBox">
        <div class="legendColorBox-inside">
          <div class="legendBox-inner" style="border:6px solid #f2dcde;">
          </div>
        </div>
      </td>
      <td class="legendLabel" > -10% - 0%</td>
      <td class="legendColorBox">
        <div class="legendColorBox-inside">
          <div class="legendBox-inner" style="border:6px solid #ffffff;">
          </div>
        </div>
      </td>
      <td class="legendLabel" > 0%</td>
      <td class="legendColorBox">
        <div class="legendColorBox-inside">
          <div class="legendBox-inner" style="border:6px solid #eaf6ec;">
          </div>
        </div>
      </td>
      <td class="legendLabel" > 0% - 10%</td>
      <td class="legendColorBox">
        <div class="legendColorBox-inside">
          <div class="legendBox-inner" style="border:6px solid #b8d9ba;">
          </div>
        </div>
      </td>
      <td class="legendLabel" > 10% - 20%</td>
      <td class="legendColorBox">
        <div class="legendColorBox-inside">
          <div class="legendBox-inner" style="border:6px solid #94af96;">
          </div>
        </div>
      </td>
      <td class="legendLabel" > &gt; 20%</td>
    </tr>
    </tbody>
  </table>
</div>

app/views/global/_daterangepicker.html.erb
<%= content_tag :span, class: 'm-subheader__daterange',
                data: {min_date: current_user.min_date, start_date: start_date, end_date: end_date},
                id: 'm_dashboard_daterangepicker' do %>
  <span class="m-subheader__daterange-label">
    <span class="m-subheader__daterange-title"></span>
    <span class="m-subheader__daterange-date m--font-brand"></span>
  </span>
  <a href="#" class="btn btn-sm btn-brand m-btn m-btn--icon m-btn--icon-only m-btn--custom m-btn--pill">
    <i class="la la-angle-down"></i>
  </a>
<% end %>

app/views/global/_errors_table.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Source Line</th>
    <th scope="col">Error</th>
  </tr>
  </thead>
  <tbody>
    <% errors.each_with_index do |element, idx| %>
      <tr>
        <th scope="row"><%= element.n %></th>
        <td><%= element.source_line %></td>
        <td><%= element.error %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/global/_horizontal_menu.html.erb
<!-- BEGIN: Brand -->
<div class="m-stack__item m-brand  m-brand--skin-dark ">
  <div class="m-stack m-stack--ver m-stack--general">
    <div class="m-stack__item m-stack__item--middle m-brand__logo">
      <%= link_to image_tag('logo_priceintelligence.png'), root_path, class: 'm-brand__logo-wrapper' %>
    </div>
    <div class="m-stack__item m-stack__item--middle m-brand__tools">
      <!-- BEGIN: Left Aside Minimize Toggle -->
      <a href="#" id="m_aside_left_minimize_toggle" onclick="return false;"
         class="m-brand__icon m-brand__toggler m-brand__toggler--left m--visible-desktop-inline-block">
        <span></span>
      </a>
      <!-- END -->
      <!-- BEGIN: Responsive Aside Left Menu Toggler -->
      <a href="#" id="m_aside_left_offcanvas_toggle" onclick="return false;"
         class="m-brand__icon m-brand__toggler m-brand__toggler--left m--visible-tablet-and-mobile-inline-block">
        <span></span>
      </a>
      <!-- END -->
      <!-- BEGIN: Responsive Header Menu Toggler -->
      <a href="#" id="m_aside_header_menu_mobile_toggle" onclick="return false;"
         class="m-brand__icon m-brand__toggler m--visible-tablet-and-mobile-inline-block">
        <span></span>
      </a>
      <!-- END -->
      <!-- BEGIN: Topbar Toggler -->
      <a href="#" id="m_aside_header_topbar_mobile_toggle" onclick="return false;"
         class="m-brand__icon m--visible-tablet-and-mobile-inline-block">
        <i class="flaticon-more"></i>
      </a>
      <!-- BEGIN: Topbar Toggler -->
    </div>
  </div>
</div>
<!-- END: Brand -->
<div class="m-stack__item m-stack__item--fluid m-header-head" id="m_header_nav">
  <!-- BEGIN: Horizontal Menu -->
  <button class="m-aside-header-menu-mobile-close  m-aside-header-menu-mobile-close--skin-dark"
          id="m_aside_header_menu_mobile_close_btn">
    <i class="la la-close"></i>
  </button>
  <div id="m_header_menu" class="m-header-menu m-aside-header-menu-mobile m-aside-header-menu-mobile--offcanvas m-header-menu--skin-light m-header-menu--submenu-skin-light m-aside-header-menu-mobile--skin-dark m-aside-header-menu-mobile--submenu-skin-dark">
    <ul class="m-menu__nav  m-menu__nav--submenu-arrow ">
      <%= content_tag :li, class: "m-menu__item  m-menu__item--submenu m-menu__item--rel" do %>
        <%= link_to root_path, class: "m-menu__link m-menu__toggle" do %>
          <%= content_tag :span, :class => "m-menu__link-title" do %>
            <%= content_tag :span, :class => "m-menu__link-wrap" do %>
              <%= content_tag :span, t('global.menu.overview'), :class => "m-menu__link-text" %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <li class="m-menu__item  m-menu__item--submenu m-menu__item--rel dropdown" data-menu-submenu-toggle="click"
          data-redirect="true" aria-haspopup="true">
        <a href="#" class="m-menu__link m-menu__toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="m-menu__link-text"><%= t('global.menu.benchmark')%></span>
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <% current_user.available_root_categories.each do |category| %>
            <li><%= link_to category, benchmark_path(category: category) %></li>
          <% end %>
        </ul>
      </li>
      <li class="m-menu__item  m-menu__item--submenu m-menu__item--rel dropdown" data-menu-submenu-toggle="click"
          data-redirect="true" aria-haspopup="true">
        <a href="#" class="m-menu__link m-menu__toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="m-menu__link-text"><%= t('global.menu.map_page')%></span>
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <% current_user.available_ecommerces.each do |ecommerce| %>
            <li><%= link_to ecommerce[1], map_path(page: ecommerce[0]) %></li>
          <% end %>
        </ul>
      </li>
      <li class="m-menu__item  m-menu__item--submenu m-menu__item--rel dropdown" data-menu-submenu-toggle="click"
          data-redirect="true" aria-haspopup="true">
        <a href="#" class="m-menu__link m-menu__toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="m-menu__link-text"><%= t('global.menu.price_evolution')%></span>
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <% current_user.available_root_categories.each do |category| %>
            <li><%= link_to category, price_evolution_path(category: category) %></li>
          <% end %>
        </ul>
      </li>
      <li class="m-menu__item  m-menu__item--submenu m-menu__item--rel">
        <%= link_to product_evolution_path, class: "m-menu__link m-menu__toggle" do %>
          <span class="m-menu__link-title">
            <span class="m-menu__link-wrap">
              <span class="m-menu__link-text"><%= t('global.menu.product_evolution') %></span>
            </span>
          </span>
        <% end %>
      </li>
      <%= content_tag :li, class: "m-menu__item  m-menu__item--submenu m-menu__item--rel" do %>
        <%= link_to files_path, class: "m-menu__link m-menu__toggle" do %>
          <%= content_tag :span, :class => "m-menu__link-title" do %>
            <%= content_tag :span, :class => "m-menu__link-wrap" do %>
              <%= content_tag :span, t('global.menu.files'), :class => "m-menu__link-text" %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <% if current_user.admin? %>
        <%= content_tag :li, class: "m-menu__item  m-menu__item--submenu m-menu__item--rel" do %>
          <%= link_to admin_root_path, class: "m-menu__link m-menu__toggle" do %>
            <%= content_tag :span, :class => "m-menu__link-title" do %>
              <%= content_tag :span, :class => "m-menu__link-wrap" do %>
                <%= content_tag :span, t('global.menu.admin'), :class => "m-menu__link-text" %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div id="m_header_topbar" class="m-topbar  m-stack m-stack--ver m-stack--general">
    <div class="m-stack__item m-topbar__nav-wrapper">
      <ul class="m-topbar__nav m-nav m-nav--inline">
        <li class="m-nav__item m-dropdown m-dropdown--large m-dropdown--arrow m-dropdown--align-center m-dropdown--mobile-full-width m-dropdown--skin-light	m-list-search m-list-search--skin-light"
            data-dropdown-toggle="click" data-dropdown-persistent="true" id="m_quicksearch" data-search-type="dropdown">
          <%= link_to destroy_user_session_path, title: t('global.menu.logout'), class: "m-nav__link" do %>
            <span class="m-nav__link-icon">
              <span class="fa fa-power-off text-link"></span>
            </span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <!-- END: Horizontal Menu -->
  <!-- BEGIN: Topbar -->
  <!-- SEARCH: Topbar
  <div id="m_header_topbar" class="m-topbar  m-stack m-stack--ver m-stack--general">
    <div class="m-stack__item m-topbar__nav-wrapper">
      <ul class="m-topbar__nav m-nav m-nav--inline">
        <li class="m-nav__item m-dropdown m-dropdown--large m-dropdown--arrow m-dropdown--align-center m-dropdown--mobile-full-width m-dropdown--skin-light	m-list-search m-list-search--skin-light"
            data-dropdown-toggle="click" data-dropdown-persistent="true" id="m_quicksearch" data-search-type="dropdown">
          <a href="#" class="m-nav__link m-dropdown__toggle">
            <span class="m-nav__link-icon">
              <i class="flaticon-search-1"></i>
            </span>
          </a>
          <div class="m-dropdown__wrapper">
            <span class="m-dropdown__arrow m-dropdown__arrow--center"></span>
            <div class="m-dropdown__inner ">
              <div class="m-dropdown__header">
                <form class="m-list-search__form">
                  <div class="m-list-search__form-wrapper">
                    <span class="m-list-search__form-input-wrapper">
                      <input id="m_quicksearch_input" autocomplete="off" type="text" name="q" class="m-list-search__form-input" value="" placeholder="Search...">
                    </span>
                    <span class="m-list-search__form-icon-close" id="m_quicksearch_close">
                      <i class="la la-remove"></i>
                    </span>
                  </div>
                </form>
              </div>
              <div class="m-dropdown__body">
                <div class="m-dropdown__scrollable m-scrollable" data-scrollable="true"
                     data-max-height="300" data-mobile-max-height="200">
                  <div class="m-dropdown__content"></div>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
  -->
  <!-- END: Topbar -->
</div>

app/views/global/_reset_button.html.erb
<div class="m-menu__section-text form-check menu-filter-check" role="tablist">
  <div class="card">
    <div class="m-content mt-4">
      <span class="btn btn-block btn-outline-dark reset-form">
        <%=t('global.reset_filters')%>
      </span>
    </div>
  </div>
</div>

app/views/global/_subheader.html.erb
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
  <div class="d-flex align-items-center">
    <div class="mr-auto">
      <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
          <li class="breadcrumb-item active" aria-current="page"><%= title %></li>
        </ol>
      </nav>
      <h3 class="m-subheader__title ">
        <%= title %>
      </h3>
    </div>
    <%= render(partial: 'global/daterangepicker', locals: {start_date: start_date, end_date: end_date}) %>
  </div>
</div>
<!-- END: Subheader -->

app/views/global/_warnings.html.erb
<% @warnings.each do |warning| %>
  <% if [:ecommerces, :brands].include?(warning) %>
    <div class="alert alert-<%=warning == :ecommerces ? 'danger' : 'warning'%> mx-auto w-50 mt-5" role="alert">
      <h3 class="alert-heading"><%=t(".#{warning}.heading")%></h3>
      <h4><%=t(".#{warning}.title")%></h4>
      <hr>
      <p class="mb-0"><%=t(".#{warning}.description")%></p>
    </div>
  <% end %>
<% end %>

app/views/global/index.js.erb
<% title            = local_assigns[:title] %>
<% n_templates      = local_assigns[:n_templates] || 1 %>
<% templates        = "index" if local_assigns[:templates].nil? %>
<% bind_elements    = local_assigns[:bind_elements] || 'main-page' %>

<% if title %>
  $('h3.m-subheader__title').text('<%= title %>');
  $('li.breadcrumb-item').filter('.active').text('<%= title %>');
<% end %>

<% n_templates.times do |n| %>
  <% rendered_template = j(render "#{index_folder}/#{templates[n]}") %>
  $('#<%= bind_elements[n] %>').replaceWith("<%= rendered_template %>");
<% end %>

<%= "setBindings(#{get_bindings.to_a});".html_safe unless get_bindings.blank? %>
$('.fixed').stickySort({fixedOffset: 70});